# fly.toml app configuration file generated for kitty-keeper on 2024-01-17T13:12:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kitty-keeper"
primary_region = "otp"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
