# fly.toml app configuration file generated for kitty-keeper on 2024-01-17T13:12:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kitty-keeper"
primary_region = "otp"
[build]
  builder = "paketobuildpacks/builder:base"
[env]
  PORT = "8080"
[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
      handlers = ["tls", "http"]
      start_port = 8080
      end_port = 8085
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
[[vm]]
  cpu_kind = "shared"
  size = "shared-cpu-1x"
  memory_mb = 512
  cpus = 2
  
